[package]
name = "utoipa-validate-gen"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.67"
quote = "1.0.33"
regex = "1.9.5"
syn = { version = "2.0.33", features = ["full"] }
utoipa = "3.5.0"
